var f="http://localhost:3000",a=class{constructor(e=f){this.base=e}async _fetch(e,i={}){let r=await fetch(`${this.base}${e}`,{mode:"cors",...i});if(!r.ok)throw new Error(`${e}: ${r.status} ${r.statusText}`);return r.json()}getUserIdByEmail(e){return this._fetch(`/api/getUserId?email=${encodeURIComponent(e)}`)}getServices(e){return this._fetch(`/api/getServices?email=${encodeURIComponent(e)}`)}isBookmarkSaved(e,i){return this._fetch("/api/isBookmarkSaved",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:e,title:i})}).then(r=>r.saved===!0).catch(()=>!1)}insertBookmark(e){return this._fetch("/api/insertBookmark",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(e)})}};var h=()=>new Promise((t,e)=>{chrome.runtime.sendMessage({type:"getUserProfile"},i=>{i?.profile?t(i.profile):e(new Error(i?.error||"Failed to get profile"))})});var s=t=>t.toString().padStart(2,"0"),g=()=>{let t=new Date;return`${t.getFullYear()}-${s(t.getMonth()+1)}-${s(t.getDate())} ${s(t.getHours())}:${s(t.getMinutes())}:${s(t.getSeconds())}`},o=(t,e=document)=>e.querySelector(t),m=(t="")=>t.replaceAll('"',"&quot;");var u={login:o("#login-section"),user:o("#user-section"),service:o("#service-section"),renderLogin(t){this.user.innerHTML=`<strong>\u30ED\u30B0\u30A4\u30F3:</strong> ${t}`,this.login.innerHTML=""},renderServiceSelect(t){this.service.innerHTML=`
      <select id="service-select" style="width:100%">
        <option value="" disabled selected>-- \u30B5\u30FC\u30D3\u30B9\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044 --</option>
        ${t.map(({id:e,title:i})=>`<option value="${e}">${i}</option>`).join("")}
      </select>`,this.service.style.marginTop="10px"},renderMetaForm(t,e){let i=document.createElement("div");i.id="meta-form",i.style.marginTop="10px",i.innerHTML=`${r("\u30BF\u30A4\u30C8\u30EB","meta-title",t.title)}
      ${r("\u8AAC\u660E","meta-description",t.description,!0)}
      ${r("URL","meta-url",t.url)}
      ${r("Favicon URL","meta-favicon",t.favicon_url)}
      ${r("Twitter\u753B\u50CFURL","meta-twitter-img",t.twitter_image_url)}
      ${r("\u516C\u958B\u65E5","meta-publish-date",(t.publish_date??"").slice(0,10),!1,"date")}
      <button id="save-btn" style="width:100%;margin-top:10px">\u4FDD\u5B58</button>`,document.body.appendChild(i),o("#save-btn").onclick=e;function r(c,l,d="",p=!1,v="text"){return p?`<label>${c}</label><br><textarea id="${l}" rows="3" style="width:100%">${m(d)}</textarea><br><br>`:`<label>${c}</label><br><input id="${l}" type="${v}" value="${m(d)}" style="width:100%"><br><br>`}}};var n=class{constructor(){this.api=new a,this.userId=null,this.meta=null,this.tabId=null}async init(){try{let{email:e}=await h();u.renderLogin(e),this.userId=(await this.api.getUserIdByEmail(e)).id;let{services:i}=await this.api.getServices(e);u.renderServiceSelect(i),await this.scrapeActiveTab();let r=await this.api.isBookmarkSaved(this.userId,this.meta.title);this.updateIcon(r)}catch(e){console.error("PopupApp init",e),alert("\u521D\u671F\u5316\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002\u8A73\u7D30\u306F\u30B3\u30F3\u30BD\u30FC\u30EB\u3092\u3054\u78BA\u8A8D\u304F\u3060\u3055\u3044\u3002")}}async scrapeActiveTab(){let[e]=await chrome.tabs.query({active:!0,currentWindow:!0});if(!e||e.url.startsWith("chrome://"))throw new Error("Unsupported page");this.tabId=e.id;let[{result:i}]=await chrome.scripting.executeScript({target:{tabId:this.tabId},func:()=>{let r=(d,p="name")=>document.querySelector(`meta[${p}="${d}"]`)?.content,c=[...document.querySelectorAll('link[rel*="icon"]')][0]?.href,l=r("article:published_time","property")||r("og:published_time","property")||document.querySelector("time[datetime]")?.dateTime||new Date().toISOString();return{title:document.title,description:r("description"),favicon_url:c,twitter_image_url:r("twitter:image"),publish_date:l}}});this.meta={...i,url:e.url},u.renderMetaForm(this.meta,()=>this.saveBookmark())}async saveBookmark(){let e=o("#service-select").value;if(!e)return alert("\u30B5\u30FC\u30D3\u30B9\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044\u3002");let i={title:o("#meta-title").value,description:o("#meta-description").value,url:o("#meta-url").value,favicon_url:o("#meta-favicon").value,twitter_image_url:o("#meta-twitter-img").value,publish_date:o("#meta-publish-date").value||this.meta.publish_date||g(),last_updated_user_id:this.userId,service_id:e};try{await this.api.insertBookmark(i),alert("\u30D6\u30C3\u30AF\u30DE\u30FC\u30AF\u3092\u4FDD\u5B58\u3057\u307E\u3057\u305F\u3002"),this.updateIcon(!0),chrome.storage.local.set({[i.url]:!0})}catch(r){console.error("saveBookmark",r),alert(`\u4FDD\u5B58\u306B\u5931\u6557\u3057\u307E\u3057\u305F: ${r.message}`)}}updateIcon(e){chrome.action.setIcon({path:e?"icon-saved.png":"icon-default.png",tabId:this.tabId})}};document.addEventListener("DOMContentLoaded",()=>new n().init());
