CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER
SET SEARCH_PATH = PUBLIC, PG_TEMP
AS $$
BEGIN
  INSERT INTO public.users (ID, NAME, EMAIL, IMAGE)
  VALUES (
    NEW.ID,
    COALESCE(NEW.RAW_USER_META_DATA ->> 'full_name', NEW.EMAIL),
    NEW.EMAIL,
    NEW.RAW_USER_META_DATA ->> 'avatar_url'
  )
  ON CONFLICT (ID) DO UPDATE
    SET NAME  = EXCLUDED.NAME,
        EMAIL = EXCLUDED.EMAIL,
        IMAGE = EXCLUDED.IMAGE;
  RETURN NEW;
END;
$$;

GRANT EXECUTE ON FUNCTION public.handle_new_user() TO SUPABASE_AUTH_ADMIN;

CREATE TRIGGER ON_AUTH_USER_CREATED
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();
